# Generated by Django 4.0 on 2021-12-15 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='playus.player'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='pdatagossip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gossip', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=50)),
                ('p_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playus.playdata')),
            ],
        ),
    ]
