# Generated by Django 4.0 on 2021-12-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playus', '0002_userlogin_player_pdatagossip'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdatagossip',
            name='userid',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
