# Generated by Django 4.0 on 2021-12-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playus', '0003_pdatagossip_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playdata',
            name='zoneX',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='playdata',
            name='zoneY',
            field=models.CharField(max_length=10),
        ),
    ]
