# Generated by Django 4.0 on 2021-12-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playus', '0004_alter_playdata_zonex_alter_playdata_zoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='writetime',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
