# Generated by Django 3.2.9 on 2021-12-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playus', '0005_userlogin_writetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playdata',
            name='gpsX',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='playdata',
            name='gpsY',
            field=models.FloatField(),
        ),
    ]
